
# --- Build system configuration

[build-system]
requires = [ "setuptools>=77", "setuptools_scm[toml]>=8", ]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
stooge = [
    "data/project_template/.gitignore",
    "data/project_template/*.md",
    "data/project_template/*.py",
    "data/project_template/*.toml",
    "data/project_template/inputs/.gitinclude",
    "data/example_project/*.py",
    "data/example_project/inputs/*.csv",
]

# --- Project Metadata

[project]
name = "stooge"
dynamic = ["version"]

authors = [
  { name="Derrick Chambers", email="chambers.ja.derrick@gmail.com" },
]

description = "A simple project framework to keep you from getting burned"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.12"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering",
]

keywords = ["workflow", "projects"]

# --- Dependencies

dependencies = [
    "typer",
    "jinja2",
    "tomli-w",
]

[project.optional-dependencies]

test = [
    "pytest",
    "pre-commit",
    "ruff",
]
dev = ["stooge[test]"]

[project.scripts]
stooge = "stooge.cli:app"

# --- URLs for project

[project.urls]
"Bug Tracker" = "https://github.com/d-chambers/stooge/issues"
"Documentation" = "https://github.com/d-chambers/stooge"
"Homepage" = "https://github.com/d-chambers/stooge"

[tool.pytest.ini_options]
testpaths = ["tests"]
markers = [
    "slow: tests that run very slowly, skipped by default",
]

[tool.ruff]
line-length = 88
target-version = "py312"

[tool.setuptools_scm]
